---
--- Generated by Luanalysis
--- Created by SmileYik.
--- DateTime: 2022/5/19 下午2:48
---

-- 是否开启debug模式
setting:debug(false)

-- 选择Lua脚本插件运行模式
-- Hybrid: 混合模式
-- Inside: 默认模式
-- Outside: Native模式
setting:run_mode("Hybrid")