---
--- Generated by Luanalysis
--- Created by SmileYik.
--- DateTime: 2022/5/19 下午2:48
---

-- 是否开启debug模式
setting:debug(false)

-- 选择Lua脚本插件运行模式
-- Hybrid: 混合模式
-- Inside: 默认模式
-- Outside: Native模式
setting:run_mode("Hybrid")

-- 选择Outside模式运行的lua版本
-- lua_5_4: lua5.4版本
-- luajit_2_1_0_beta3: luajit2.1.0_beta3版本
-- 在Inside模式中无效
setting:native_version("lua_5_4")