name: LuaInMinecraftBukkit
main: tk.smileyik.luainminecraftbukkit.LuaInMinecraftBukkit
version: 1.7.0
api-version: 1.13
author: SmileYik
commands:
  lua:
    permission: LuaInMinecraftBukkit.Admin
  luap:
permissions:
  LuaInMinecraftBukkit.Admin:
    default: op