---
--- Generated by Luanalysis
--- Created by miskyle.
--- DateTime: 2022/5/19 下午2:22
---

entity:setaString("I am String")
entity:setAnInt(10)
entity:setaFloat(1.555555555555555)
-- entity:setaChar(49)
entity:setaBoolean(true)
entity:setaDouble(1.55555555555555)
-- entity:setBytes({1, 2, 3, 4, 5})
entity:setDoubles(helper:toDoubleArray({1.1, 2.2, 3.3, 4.4, 5.5}))
-- entity:setChars(helper:toIntArray({46, 47, 48}))
entity:setInts(helper:toIntArray({7, 8, 9, 10}))
entity:setStrings(helper:toStringArray({"aaaaa", "bbbbbb", "cccccc"}))
entity:setEntities(helper:toArray(entity, {nil, nil, nil}))
entity:setEntity(nil)